//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.datas
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToyOrder
    {
        public int id { get; set; }
        public Nullable<int> ToyId { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> OrderId { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual toy toy { get; set; }
    }
}
